# LIB=-L/usr/informix/lib/c++
INC=-I/home/jui-hsien/Research/code/TurbulentHead/tools/Math 

CC=g++
CFLAGS=-std=c++11

all: fluentMshReader.cpp fluentMshReader.h
	$(CC) $(CFLAGS) fluentMshReader.cpp -o fluentMshReader -I /home/jui-hsien/Research/code/TurbulentHead/tools/Math
