#!/bin/sh

# This file was generated by Fluent.  To kill Fluent and all its
# related processes, run this script.  If
# Fluent exits normally, this file will be removed automatically.

if [ `/bin/uname` = HP-UX ]; then
	REMOTE_SH=remsh
else
	REMOTE_SH=rsh
fi

KILL_CMD="kill -9 "
LOCALHOST=`hostname`
if [ $LOCALHOST = juihsien-Z9PE-D8-WS ]; then $KILL_CMD 25891; else $REMOTE_SH juihsien-Z9PE-D8-WS $KILL_CMD 25891; fi
if [ $LOCALHOST = juihsien-Z9PE-D8-WS ]; then $KILL_CMD 25787; else $REMOTE_SH juihsien-Z9PE-D8-WS $KILL_CMD 25787; fi
/bin/rm -f /media/jui-hsien/General/Research/Ansys-run/code/TurbulentHead/src/cleanup-fluent-juihsien-Z9PE-D8-WS-25787.sh
